# Generated by Django 4.2.10 on 2025-06-09 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='endereço de email')),
                ('first_name', models.CharField(max_length=150, verbose_name='nome')),
                ('last_name', models.CharField(max_length=150, verbose_name='sobrenome')),
                ('role', models.CharField(choices=[('candidate', 'Candidato'), ('recruiter', 'Recrutador'), ('admin', 'Administrador')], default='candidate', max_length=20, verbose_name='perfil')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='telefone')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='foto de perfil')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='biografia')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='endereço')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=2, null=True, verbose_name='estado')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='departamento')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='cargo')),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='ID de funcionário')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='equipe')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='data de cadastro')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='último login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_custom_set', related_query_name='user_custom', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_custom_set', related_query_name='user_custom', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.user')),
            ],
            options={
                'verbose_name': 'perfil de usuário',
                'verbose_name_plural': 'perfis de usuários',
            },
        ),
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=100, null=True, verbose_name='especialização')),
                ('hiring_authority', models.BooleanField(default=False, verbose_name='autoridade para contratar')),
                ('vacancies_created', models.IntegerField(default=0, verbose_name='vagas criadas')),
                ('candidates_interviewed', models.IntegerField(default=0, verbose_name='candidatos entrevistados')),
                ('successful_hires', models.IntegerField(default=0, verbose_name='contratações bem-sucedidas')),
                ('notification_preferences', models.JSONField(default=dict, verbose_name='preferências de notificação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to='users.user')),
            ],
            options={
                'verbose_name': 'perfil de recrutador',
                'verbose_name_plural': 'perfis de recrutadores',
            },
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(blank=True, max_length=50, null=True, verbose_name='nível de escolaridade')),
                ('institution', models.CharField(blank=True, max_length=100, null=True, verbose_name='instituição')),
                ('course', models.CharField(blank=True, max_length=100, null=True, verbose_name='curso')),
                ('graduation_year', models.IntegerField(blank=True, null=True, verbose_name='ano de formação')),
                ('years_of_experience', models.IntegerField(default=0, verbose_name='anos de experiência')),
                ('current_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='cargo atual')),
                ('current_company', models.CharField(blank=True, max_length=100, null=True, verbose_name='empresa atual')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='habilidades')),
                ('desired_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='cargo desejado')),
                ('desired_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='salário desejado')),
                ('available_immediately', models.BooleanField(default=True, verbose_name='disponível imediatamente')),
                ('notice_period', models.IntegerField(default=0, verbose_name='período de aviso prévio (dias)')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='currículo')),
                ('cover_letter', models.TextField(blank=True, null=True, verbose_name='carta de apresentação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to='users.user')),
            ],
            options={
                'verbose_name': 'perfil de candidato',
                'verbose_name_plural': 'perfis de candidatos',
            },
        ),
    ]
