# Generated by Django 4.2.7 on 2025-08-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='user',
            name='compartilhar_dados',
            field=models.BooleanField(default=False, verbose_name='compartilhar dados'),
        ),
        migrations.AddField(
            model_name='user',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='complemento'),
        ),
        migrations.AddField(
            model_name='user',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='estado civil'),
        ),
        migrations.AddField(
            model_name='user',
            name='genero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='gênero'),
        ),
        migrations.AddField(
            model_name='user',
            name='nome_social',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='nome social'),
        ),
        migrations.AddField(
            model_name='user',
            name='notificacoes_email',
            field=models.BooleanField(default=True, verbose_name='notificações por email'),
        ),
        migrations.AddField(
            model_name='user',
            name='notificacoes_sms',
            field=models.BooleanField(default=False, verbose_name='notificações por SMS'),
        ),
        migrations.AddField(
            model_name='user',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='número'),
        ),
        migrations.AddField(
            model_name='user',
            name='perfil_publico',
            field=models.BooleanField(default=False, verbose_name='perfil público'),
        ),
        migrations.AddField(
            model_name='user',
            name='perfil_visivel',
            field=models.BooleanField(default=True, verbose_name='perfil visível'),
        ),
        migrations.AddField(
            model_name='user',
            name='pis',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PIS'),
        ),
        migrations.AddField(
            model_name='user',
            name='raca_cor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='raça/cor'),
        ),
        migrations.AddField(
            model_name='user',
            name='receber_convites',
            field=models.BooleanField(default=True, verbose_name='receber convites'),
        ),
        migrations.AddField(
            model_name='user',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='user',
            name='rg_emissao',
            field=models.DateField(blank=True, null=True, verbose_name='data de emissão RG'),
        ),
        migrations.AddField(
            model_name='user',
            name='rg_orgao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='órgão emissor RG'),
        ),
        migrations.AddField(
            model_name='user',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='sexo'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='whatsapp'),
        ),
    ]
