# Generated by Django 4.2.7 on 2025-08-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bairro_user_compartilhar_dados_user_complemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmado',
            field=models.BooleanField(default=False, verbose_name='email confirmado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('uniao_estavel', 'União Estável'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)')], max_length=20, null=True, verbose_name='estado civil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='genero',
            field=models.CharField(blank=True, choices=[('homem_cis', 'Homem Cisgênero'), ('homem_trans', 'Homem Transexual/Transgênero'), ('mulher_cis', 'Mulher Cisgênero'), ('mulher_trans', 'Mulher Transexual/Transgênero'), ('nao_binario', 'Não-binário'), ('outros', 'Outros'), ('prefiro_nao_responder', 'Prefiro não responder')], max_length=30, null=True, verbose_name='gênero'),
        ),
        migrations.AlterField(
            model_name='user',
            name='raca_cor',
            field=models.CharField(blank=True, choices=[('indigena', 'Indígena'), ('branca', 'Branca'), ('preta', 'Preta'), ('amarela', 'Amarela'), ('parda', 'Parda')], max_length=20, null=True, verbose_name='raça/cor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='sexo (designação ao nascer)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='telefone com WhatsApp'),
        ),
    ]
