# Generated by Django 4.2.7 on 2025-08-14 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_email_confirmado_alter_user_estado_civil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='available_immediately',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='desired_position',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='desired_salary',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='notice_period',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='endereço'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='biografia'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='experience_years',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='tempo de experiência'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='perfil público'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='telefone'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='pis',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PIS'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='foto de perfil'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='share_data',
            field=models.BooleanField(default=False, verbose_name='compartilhar dados'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data de criação'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='ano de conclusão'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='data de atualização'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200, verbose_name='empresa')),
                ('cargo', models.CharField(max_length=200, verbose_name='cargo')),
                ('inicio', models.DateField(verbose_name='data de início')),
                ('fim', models.DateField(blank=True, null=True, verbose_name='data de saída')),
                ('atual', models.BooleanField(default=False, verbose_name='trabalho atual')),
                ('atividades', models.TextField(blank=True, verbose_name='atividades e responsabilidades')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'experiência profissional',
                'verbose_name_plural': 'experiências profissionais',
                'ordering': ['-fim', '-inicio'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=200, verbose_name='instituição')),
                ('curso', models.CharField(max_length=200, verbose_name='curso')),
                ('nivel', models.CharField(choices=[('fundamental_incompleto', 'Ensino Fundamental Incompleto'), ('fundamental_completo', 'Ensino Fundamental Completo'), ('medio_incompleto', 'Ensino Médio Incompleto'), ('medio_completo', 'Ensino Médio Completo'), ('tecnico', 'Técnico'), ('superior_incompleto', 'Superior Incompleto'), ('superior_completo', 'Superior Completo'), ('pos_graduacao', 'Pós-graduação'), ('mestrado', 'Mestrado'), ('doutorado', 'Doutorado')], max_length=50, verbose_name='nível')),
                ('inicio', models.DateField(verbose_name='data de início')),
                ('fim', models.DateField(blank=True, null=True, verbose_name='data de conclusão')),
                ('em_andamento', models.BooleanField(default=False, verbose_name='em andamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'formação acadêmica',
                'verbose_name_plural': 'formações acadêmicas',
                'ordering': ['-fim', '-inicio'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('orgao', models.CharField(blank=True, max_length=200, verbose_name='órgão emissor')),
                ('emissao', models.DateField(blank=True, null=True, verbose_name='data de emissão')),
                ('validade', models.DateField(blank=True, null=True, verbose_name='data de validade')),
                ('credencial_url', models.URLField(blank=True, verbose_name='URL da credencial')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'certificação',
                'verbose_name_plural': 'certificações',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome da habilidade')),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado'), ('expert', 'Expert')], max_length=20, verbose_name='nível')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'habilidade técnica',
                'verbose_name_plural': 'habilidades técnicas',
                'ordering': ['nome'],
                'unique_together': {('user', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='SoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome da habilidade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soft_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'habilidade emocional',
                'verbose_name_plural': 'habilidades emocionais',
                'ordering': ['nome'],
                'unique_together': {('user', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=50, verbose_name='idioma')),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado'), ('fluente', 'Fluente'), ('nativo', 'Nativo')], max_length=20, verbose_name='nível')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'idioma',
                'verbose_name_plural': 'idiomas',
                'ordering': ['idioma'],
                'unique_together': {('user', 'idioma')},
            },
        ),
    ]
