# Generated by Django 4.2.7 on 2025-08-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_candidateprofile_available_immediately_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='sem_validade',
            field=models.BooleanField(default=False, verbose_name='sem data de validade'),
        ),
    ]
