# Generated by Django 4.2.7 on 2025-08-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_certification_sem_validade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='language',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='language',
            name='idioma_outro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='outro idioma'),
        ),
        migrations.AlterField(
            model_name='language',
            name='idioma',
            field=models.CharField(choices=[('portugues', 'Português'), ('ingles', 'Inglês'), ('espanhol', 'Espanhol'), ('frances', 'Francês'), ('alemao', 'Alemão'), ('italiano', 'Italiano'), ('japones', 'Japonês'), ('chines', 'Chinês'), ('coreano', 'Coreano'), ('russo', 'Russo'), ('arabe', 'Árabe'), ('outro', 'Outro')], max_length=50, verbose_name='idioma'),
        ),
        migrations.AlterUniqueTogether(
            name='language',
            unique_together={('user', 'idioma', 'idioma_outro')},
        ),
    ]
