# Generated by Django 4.2.7 on 2025-01-14 21:15

from django.db import migrations, models


def remove_duplicate_languages(apps, schema_editor):
    """Remove idiomas duplicados antes de aplicar a nova constraint."""
    Language = apps.get_model('users', 'Language')
    
    # Para cada usuário, remove idiomas duplicados mantendo apenas o primeiro
    from django.db.models import Min
    duplicates = Language.objects.values('user', 'idioma').annotate(
        min_id=Min('id')
    ).values('user', 'idioma', 'min_id')
    
    for duplicate in duplicates:
        # Mantém apenas o registro com menor ID
        Language.objects.filter(
            user_id=duplicate['user'],
            idioma=duplicate['idioma']
        ).exclude(id=duplicate['min_id']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_language_unique_together_language_idioma_outro_and_more'),
    ]

    operations = [
        # Primeiro remove duplicatas
        migrations.RunPython(remove_duplicate_languages, reverse_code=migrations.RunPython.noop),
        
        # Depois altera a constraint
        migrations.AlterUniqueTogether(
            name='language',
            unique_together={('user', 'idioma')},
        ),
    ]
