# Generated by Django 4.2.10 on 2025-06-09 19:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('under_review', 'Em Análise'), ('interview', 'Entrevista'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('withdrawn', 'Desistência')], default='pending', max_length=20, verbose_name='Status')),
                ('cover_letter', models.TextField(blank=True, null=True, verbose_name='Carta de Apresentação')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='Currículo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('recruiter_notes', models.TextField(blank=True, null=True, verbose_name='Notas do Recrutador')),
            ],
            options={
                'verbose_name': 'Candidatura',
                'verbose_name_plural': 'Candidaturas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Pontuação Técnica')),
                ('experience_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Pontuação de Experiência')),
                ('cultural_fit_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Adequação Cultural')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comentários')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Avaliação de Candidatura',
                'verbose_name_plural': 'Avaliações de Candidaturas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255, verbose_name='Instituição')),
                ('degree', models.CharField(choices=[('high_school', 'Ensino Médio'), ('technical', 'Curso Técnico'), ('bachelor', 'Graduação'), ('specialization', 'Especialização'), ('mba', 'MBA'), ('master', 'Mestrado'), ('doctorate', 'Doutorado'), ('post_doctorate', 'Pós-Doutorado'), ('other', 'Outro')], max_length=20, verbose_name='Grau')),
                ('field_of_study', models.CharField(max_length=255, verbose_name='Área de Estudo')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('is_current', models.BooleanField(default=False, verbose_name='Cursando Atualmente')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Formação Educacional',
                'verbose_name_plural': 'Formações Educacionais',
                'ordering': ['-end_date', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Resumo Profissional')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='Habilidades')),
                ('languages', models.TextField(blank=True, null=True, verbose_name='Idiomas')),
                ('certifications', models.TextField(blank=True, null=True, verbose_name='Certificações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Currículo Detalhado',
                'verbose_name_plural': 'Currículos Detalhados',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255, verbose_name='Empresa')),
                ('position', models.CharField(max_length=255, verbose_name='Cargo')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('is_current', models.BooleanField(default=False, verbose_name='Trabalho Atual')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('achievements', models.TextField(blank=True, null=True, verbose_name='Realizações')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='applications.resume', verbose_name='Currículo')),
            ],
            options={
                'verbose_name': 'Experiência Profissional',
                'verbose_name_plural': 'Experiências Profissionais',
                'ordering': ['-end_date', '-start_date'],
            },
        ),
    ]
