# Generated by Django 4.2.10 on 2025-06-09 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacancies', '0001_initial'),
        ('applications', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_resume', to='users.userprofile', verbose_name='Candidato'),
        ),
        migrations.AddField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='applications.resume', verbose_name='Currículo'),
        ),
        migrations.AddField(
            model_name='applicationevaluation',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='applications.application', verbose_name='Candidatura'),
        ),
        migrations.AddField(
            model_name='applicationevaluation',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_made', to='users.userprofile', verbose_name='Avaliador'),
        ),
        migrations.AddField(
            model_name='application',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.userprofile', verbose_name='Candidato'),
        ),
        migrations.AddField(
            model_name='application',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='vacancies.vacancy', verbose_name='Vaga'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationevaluation',
            unique_together={('application', 'evaluator')},
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('candidate', 'vacancy')},
        ),
    ]
