# Generated by Django 4.2.7 on 2025-08-15 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationComplementaryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabalha_atualmente', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, verbose_name='Trabalha atualmente no hospital/unidade')),
                ('funcao_atual', models.CharField(blank=True, max_length=255, null=True, verbose_name='Função atual')),
                ('experiencia_area', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, verbose_name='Possui experiência na área da vaga')),
                ('descricao_experiencia', models.TextField(blank=True, null=True, verbose_name='Descrição da experiência na área')),
                ('ultima_funcao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Última função exercida')),
                ('tempo_experiencia', models.CharField(choices=[('menos_6_meses', 'Menos de 6 meses'), ('6_meses_1_ano', '6 meses a 1 ano'), ('1_2_anos', '1 a 2 anos'), ('2_5_anos', '2 a 5 anos'), ('acima_5_anos', 'Acima de 5 anos')], max_length=20, verbose_name='Tempo de experiência')),
                ('disponibilidade_manha', models.BooleanField(default=False, verbose_name='Disponibilidade Manhã')),
                ('disponibilidade_tarde', models.BooleanField(default=False, verbose_name='Disponibilidade Tarde')),
                ('disponibilidade_noite', models.BooleanField(default=False, verbose_name='Disponibilidade Noite')),
                ('disponibilidade_comercial', models.BooleanField(default=False, verbose_name='Disponibilidade Horário Comercial')),
                ('disponibilidade_plantao_dia', models.BooleanField(default=False, verbose_name='Disponibilidade Plantão 12x36 (dia)')),
                ('disponibilidade_plantao_noite', models.BooleanField(default=False, verbose_name='Disponibilidade Plantão 12x36 (noite)')),
                ('inicio_imediato', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, verbose_name='Disponibilidade para início imediato')),
                ('trabalhou_acqua', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, verbose_name='Já trabalhou no Instituto ACQUA')),
                ('area_cargo_acqua', models.CharField(blank=True, max_length=255, null=True, verbose_name='Área/Cargo no ACQUA')),
                ('data_desligamento', models.DateField(blank=True, null=True, verbose_name='Data de desligamento do ACQUA')),
                ('parentes_instituicao', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, verbose_name='Possui parentes na instituição')),
                ('grau_parentesco', models.CharField(blank=True, choices=[('avo', 'Avô (a)'), ('pai', 'Pai'), ('mae', 'Mãe'), ('filho', 'Filho (a)'), ('irmao', 'Irmão (a)'), ('tio', 'Tio (a)'), ('sobrinho', 'Sobrinho (a)'), ('primo', 'Primo (a)'), ('conjuge', 'Cônjuge'), ('enteado', 'Enteado (a)'), ('sogro', 'Sogro (a)'), ('genro', 'Genro'), ('nora', 'Nora'), ('neto', 'Neto (a)'), ('cunhado', 'Cunhado (a)'), ('nenhum', 'Nenhum')], max_length=20, null=True, verbose_name='Grau de parentesco')),
                ('nome_parente_setor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do parente e setor')),
                ('declaracao_veracidade', models.BooleanField(default=False, verbose_name='Declaração de veracidade')),
                ('declaracao_edital', models.BooleanField(default=False, verbose_name='Declaração de concordância com edital')),
                ('autorizacao_dados', models.BooleanField(default=False, verbose_name='Autorização de uso de dados')),
                ('data_declaracao', models.CharField(max_length=10, verbose_name='Data da declaração')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complementary_info', to='applications.application', verbose_name='Candidatura')),
            ],
            options={
                'verbose_name': 'Informação Complementar da Candidatura',
                'verbose_name_plural': 'Informações Complementares das Candidaturas',
            },
        ),
    ]
