# Generated by Django 4.2.7 on 2025-08-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_applicationcomplementaryinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcomplementaryinfo',
            name='atestado_pcd',
            field=models.FileField(blank=True, null=True, upload_to='pcd_atestados/', verbose_name='Atestado PCD'),
        ),
        migrations.AddField(
            model_name='applicationcomplementaryinfo',
            name='cid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CID'),
        ),
        migrations.AddField(
            model_name='applicationcomplementaryinfo',
            name='conselho_regional',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Conselho regional'),
        ),
        migrations.AddField(
            model_name='applicationcomplementaryinfo',
            name='descricao_adaptacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição das adaptações'),
        ),
        migrations.AddField(
            model_name='applicationcomplementaryinfo',
            name='is_pcd',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='É PCD'),
        ),
        migrations.AddField(
            model_name='applicationcomplementaryinfo',
            name='necessita_adaptacoes',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Necessita adaptações'),
        ),
        migrations.AddField(
            model_name='applicationcomplementaryinfo',
            name='numero_registro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do registro'),
        ),
        migrations.AddField(
            model_name='applicationcomplementaryinfo',
            name='validade_registro',
            field=models.DateField(blank=True, null=True, verbose_name='Validade do registro'),
        ),
    ]
