# Generated by Django 4.2.7 on 2025-08-19 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_language_unique_together'),
        ('applications', '0004_applicationcomplementaryinfo_atestado_pcd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='applications.application', verbose_name='Candidatura')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_applications', to='users.userprofile', verbose_name='Recrutador')),
            ],
            options={
                'verbose_name': 'Candidatura Favorita',
                'verbose_name_plural': 'Candidaturas Favoritas',
                'ordering': ['-created_at'],
                'unique_together': {('application', 'recruiter')},
            },
        ),
    ]
