# Generated by Django 4.2.7 on 2025-01-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_applicationfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcomplementaryinfo',
            name='disponibilidade_plantao_12x60_dia',
            field=models.BooleanField(default=False, verbose_name='Disponibilidade Plantão 12x60 (dia)'),
        ),
        migrations.AddField(
            model_name='applicationcomplementaryinfo',
            name='disponibilidade_plantao_12x60_noite',
            field=models.BooleanField(default=False, verbose_name='Disponibilidade Plantão 12x60 (noite)'),
        ),
    ]
