# Generated by Django 4.2.10 on 2025-06-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('action', models.CharField(choices=[('create', 'Criação'), ('update', 'Atualização'), ('delete', 'Exclusão'), ('view', 'Visualização'), ('login', 'Login'), ('logout', 'Logout'), ('other', 'Outro')], max_length=10, verbose_name='Ação')),
                ('content_type', models.CharField(max_length=255, verbose_name='Tipo de Conteúdo')),
                ('object_id', models.CharField(max_length=255, verbose_name='ID do Objeto')),
                ('object_repr', models.CharField(max_length=255, verbose_name='Representação do Objeto')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Alterações')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('code', models.CharField(max_length=50, verbose_name='Código')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['hospital', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('subject', models.CharField(max_length=255, verbose_name='Assunto')),
                ('body_html', models.TextField(verbose_name='Corpo HTML')),
                ('body_text', models.TextField(verbose_name='Corpo Texto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('variables', models.JSONField(default=list, verbose_name='Variáveis Disponíveis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Template de E-mail',
                'verbose_name_plural': 'Templates de E-mail',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('address', models.TextField(verbose_name='Endereço')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=2, verbose_name='Estado')),
                ('postal_code', models.CharField(max_length=10, verbose_name='CEP')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hospital_logos/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitais',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('notification_type', models.CharField(choices=[('info', 'Informação'), ('success', 'Sucesso'), ('warning', 'Aviso'), ('error', 'Erro')], default='info', max_length=10, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Leitura')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL')),
                ('related_object_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Objeto Relacionado')),
                ('related_object_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID do Objeto Relacionado')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Chave')),
                ('value', models.TextField(verbose_name='Valor')),
                ('value_type', models.CharField(choices=[('string', 'Texto'), ('integer', 'Número Inteiro'), ('float', 'Número Decimal'), ('boolean', 'Booleano'), ('json', 'JSON'), ('date', 'Data'), ('datetime', 'Data e Hora')], default='string', max_length=20, verbose_name='Tipo de Valor')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('is_public', models.BooleanField(default=False, verbose_name='Público')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Informação'), ('warning', 'Aviso'), ('error', 'Erro'), ('critical', 'Crítico')], default='info', max_length=10, verbose_name='Nível')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('source', models.CharField(max_length=255, verbose_name='Fonte')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('request_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Caminho da Requisição')),
                ('request_method', models.CharField(blank=True, max_length=10, null=True, verbose_name='Método da Requisição')),
                ('additional_data', models.JSONField(blank=True, default=list, null=True, verbose_name='Dados Adicionais')),
            ],
            options={
                'verbose_name': 'Log do Sistema',
                'verbose_name_plural': 'Logs do Sistema',
                'ordering': ['-timestamp'],
            },
        ),
    ]
