version: '3.8'

services:
  db:
    restart: unless-stopped 
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: rh_acqua_db
      POSTGRES_USER: rh_acqua_user
      POSTGRES_PASSWORD: rh_acqua_password
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rh_acqua_user -d rh_acqua_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    restart: unless-stopped
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    restart: unless-stopped
    build: .
    command: sh -c "python manage.py collectstatic --noinput && sleep 5 && gunicorn --bind 0.0.0.0:8000 hr_system.wsgi:application"   
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
        # --- ALTERAÇÃO 2: DEBUG=False ---
        - DEBUG=False
        # --- ALTERAÇÃO 3: ALLOWED_HOSTS LIMPO ---
        - ALLOWED_HOSTS=rh.institutoacqua.org.br,www.rh.institutoacqua.org.br
        - DJANGO_SETTINGS_MODULE=hr_system.settings
        - DB_ENGINE=django.db.backends.postgresql
        - DB_NAME=rh_acqua_db
        - DB_USER=rh_acqua_user
        - DB_PASSWORD=rh_acqua_password
        - DB_HOST=db
        - DB_PORT=5432
        - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    #healthcheck:
      #test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      #interval: 30s
      #timeout: 10s
      #retries: 3

  celery:
    restart: unless-stopped
    build: .
    command: celery -A hr_system worker -l warning
    volumes:
      - .:/app
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,158.220.108.114,vmi2744085.contaboserver.net,rh.institutoacqua.org.br
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=rh_acqua_db
      - DB_USER=rh_acqua_user
      - DB_PASSWORD=rh_acqua_password
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  celery-beat:
    restart: unless-stopped
    build: .
    command: celery -A hr_system beat -l warning
    volumes:
      - .:/app
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,158.220.108.114,vmi2744085.contaboserver.net,rh.institutoacqua.org.br
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=rh_acqua_db
      - DB_USER=rh_acqua_user
      - DB_PASSWORD=rh_acqua_password
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  static_volume:
  media_volume:
