#!/bin/bash

echo "🧪 TESTE COM TODOS OS CAMPOS OBRIGATÓRIOS"
echo "========================================"

echo ""
echo "📋 CAMPOS OBRIGATÓRIOS IDENTIFICADOS:"
echo "====================================="
echo "✅ title (CharField, max_length=200)"
echo "✅ description (TextField)"
echo "✅ requirements (TextField)"
echo "✅ hospital (ForeignKey - ID: 1)"
echo "✅ department (ForeignKey - ID: 3)"
echo "✅ location (CharField, max_length=200)"
echo "✅ contract_type (CharField - choices)"
echo "✅ experience_level (CharField - choices)"
echo ""
echo "📋 CAMPOS OPCIONAIS:"
echo "==================="
echo "• benefits (TextField, blank=True)"
echo "• category (ForeignKey, null=True)"
echo "• skills (ManyToManyField)"
echo "• salary_range_min/max (DecimalField, blank=True)"
echo "• is_salary_visible (BooleanField, default=False)"
echo "• is_remote (BooleanField, default=False)"
echo "• status (CharField, default=DRAFT)"

echo ""
echo "🎯 DADOS VÁLIDOS PARA TESTE:"
echo "==========================="
echo "• Hospital: ID 1 (Hospital Municipal Materno Infantil da Serra)"
echo "• Departamento: ID 3 (Administração)"
echo "• Categoria: ID 1 (Teste) - OPCIONAL"
echo ""
echo "• contract_type: 'full_time', 'part_time', 'temporary', 'internship'"
echo "• experience_level: 'entry', 'junior', 'mid', 'senior', 'specialist'"

echo ""
echo "🔍 POSSÍVEIS CAUSAS DO ERRO DE VALIDAÇÃO:"
echo "========================================="
echo "1. ❌ Campo 'title' muito longo (>200 caracteres)"
echo "2. ❌ Campo 'location' muito longo (>200 caracteres)"
echo "3. ❌ Valores inválidos para 'contract_type' ou 'experience_level'"
echo "4. ❌ Relacionamento inválido entre hospital e departamento"
echo "5. ❌ Campos obrigatórios vazios (mesmo que pareçam preenchidos)"
echo "6. ❌ Formato de dados incorreto (números, datas, etc.)"

echo ""
echo "🧪 TESTE MANUAL RECOMENDADO:"
echo "==========================="
echo "1. Acesse: https://rh.institutoacqua.org.br/vacancies/vacancy/create/"
echo "2. Faça login como recrutador"
echo "3. Preencha APENAS os campos obrigatórios:"
echo "   • Título: 'Vaga de Teste'"
echo "   • Descrição: 'Descrição de teste'"
echo "   • Requisitos: 'Requisitos de teste'"
echo "   • Hospital: 'Hospital Municipal Materno Infantil da Serra'"
echo "   • Departamento: 'Administração'"
echo "   • Localização: 'São Paulo, SP'"
echo "   • Tipo de Contrato: 'Tempo integral'"
echo "   • Nível de Experiência: 'Júnior'"
echo "4. Clique em 'Salvar'"
echo "5. Verifique se há mensagens de erro específicas"

echo ""
echo "✅ Script de análise concluído!"


