# Generated by Django 4.2.10 on 2025-06-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('start_date', models.DateTimeField(verbose_name='Data de Início')),
                ('end_date', models.DateTimeField(verbose_name='Data de Término')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('target_roles', models.JSONField(blank=True, default=list, null=True, verbose_name='Perfis Alvo')),
                ('is_important', models.BooleanField(default=False, verbose_name='Importante')),
            ],
            options={
                'verbose_name': 'Anúncio',
                'verbose_name_plural': 'Anúncios',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', verbose_name='Arquivo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('content_type', models.CharField(max_length=100, verbose_name='Tipo de Conteúdo')),
                ('size', models.PositiveIntegerField(verbose_name='Tamanho (bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ícone')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('content_type', models.CharField(max_length=100, verbose_name='Tipo de Conteúdo')),
                ('object_id', models.CharField(max_length=100, verbose_name='ID do Objeto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('layout', models.JSONField(default=dict, verbose_name='Layout')),
                ('is_default', models.BooleanField(default=False, verbose_name='Padrão')),
                ('is_public', models.BooleanField(default=False, verbose_name='Público')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('question', models.CharField(max_length=255, verbose_name='Pergunta')),
                ('answer', models.TextField(verbose_name='Resposta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('feedback_type', models.CharField(choices=[('bug', 'Bug'), ('feature', 'Sugestão de Funcionalidade'), ('improvement', 'Melhoria'), ('other', 'Outro')], max_length=20, verbose_name='Tipo de Feedback')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('new', 'Novo'), ('in_progress', 'Em Andamento'), ('resolved', 'Resolvido'), ('closed', 'Fechado'), ('rejected', 'Rejeitado')], default='new', max_length=20, verbose_name='Status')),
                ('resolution', models.TextField(blank=True, null=True, verbose_name='Resolução')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ícone')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('required_permissions', models.JSONField(blank=True, default=list, null=True, verbose_name='Permissões Necessárias')),
                ('required_roles', models.JSONField(blank=True, default=list, null=True, verbose_name='Perfis Necessários')),
            ],
            options={
                'verbose_name': 'Item de Menu',
                'verbose_name_plural': 'Itens de Menu',
                'ordering': ['parent__order', 'parent__id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('color', models.CharField(default='#3498db', max_length=7, verbose_name='Cor')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('widget_type', models.CharField(choices=[('chart', 'Gráfico'), ('table', 'Tabela'), ('metric', 'Métrica'), ('list', 'Lista'), ('custom', 'Personalizado')], max_length=20, verbose_name='Tipo de Widget')),
                ('data_source', models.CharField(max_length=255, verbose_name='Fonte de Dados')),
                ('configuration', models.JSONField(default=dict, verbose_name='Configuração')),
                ('position_x', models.PositiveIntegerField(default=0, verbose_name='Posição X')),
                ('position_y', models.PositiveIntegerField(default=0, verbose_name='Posição Y')),
                ('width', models.PositiveIntegerField(default=1, verbose_name='Largura')),
                ('height', models.PositiveIntegerField(default=1, verbose_name='Altura')),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
                'ordering': ['dashboard', 'position_y', 'position_x'],
            },
        ),
    ]
