# Generated by Django 4.2.10 on 2025-06-09 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('is_public', models.BooleanField(default=False, verbose_name='Público')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('layout', models.JSONField(blank=True, null=True, verbose_name='Layout')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('metric_type', models.CharField(choices=[('count', 'Contagem'), ('percentage', 'Porcentagem'), ('average', 'Média'), ('sum', 'Soma'), ('min', 'Mínimo'), ('max', 'Máximo')], max_length=20, verbose_name='Tipo de Métrica')),
                ('data_source', models.CharField(max_length=255, verbose_name='Fonte de Dados')),
                ('query', models.TextField(blank=True, null=True, verbose_name='Consulta')),
                ('parameters', models.JSONField(blank=True, null=True, verbose_name='Parâmetros')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Métrica',
                'verbose_name_plural': 'Métricas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('context', models.JSONField(blank=True, null=True, verbose_name='Contexto')),
            ],
            options={
                'verbose_name': 'Valor de Métrica',
                'verbose_name_plural': 'Valores de Métricas',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('report_type', models.CharField(choices=[('recruitment_funnel', 'Funil de Recrutamento'), ('time_to_hire', 'Tempo de Contratação'), ('source_efficiency', 'Eficiência de Fontes'), ('interviewer_performance', 'Desempenho de Entrevistadores'), ('vacancy_status', 'Status de Vagas'), ('candidate_demographics', 'Demografia de Candidatos'), ('custom', 'Personalizado')], max_length=50, verbose_name='Tipo de Relatório')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='Agendado')),
                ('schedule_frequency', models.CharField(blank=True, choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('quarterly', 'Trimestral')], max_length=20, null=True, verbose_name='Frequência')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Última Execução')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='Próxima Execução')),
                ('parameters', models.JSONField(blank=True, null=True, verbose_name='Parâmetros')),
                ('preferred_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('html', 'HTML')], default='pdf', max_length=10, verbose_name='Formato Preferido')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Execução')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Arquivo de Resultado')),
            ],
            options={
                'verbose_name': 'Execução de Relatório',
                'verbose_name_plural': 'Execuções de Relatórios',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('report_type', models.CharField(choices=[('recruitment_funnel', 'Funil de Recrutamento'), ('time_to_hire', 'Tempo de Contratação'), ('source_efficiency', 'Eficiência de Fontes'), ('interviewer_performance', 'Desempenho de Entrevistadores'), ('vacancy_status', 'Status de Vagas'), ('candidate_demographics', 'Demografia de Candidatos'), ('custom', 'Personalizado')], max_length=50, verbose_name='Tipo de Relatório')),
                ('template_file', models.FileField(blank=True, null=True, upload_to='report_templates/', verbose_name='Arquivo de Template')),
                ('html_template', models.TextField(blank=True, null=True, verbose_name='Template HTML')),
                ('parameters_schema', models.JSONField(blank=True, null=True, verbose_name='Esquema de Parâmetros')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Template de Relatório',
                'verbose_name_plural': 'Templates de Relatórios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('widget_type', models.CharField(choices=[('chart_bar', 'Gráfico de Barras'), ('chart_line', 'Gráfico de Linhas'), ('chart_pie', 'Gráfico de Pizza'), ('chart_donut', 'Gráfico de Rosca'), ('kpi', 'Indicador de Desempenho'), ('table', 'Tabela'), ('list', 'Lista'), ('text', 'Texto')], max_length=20, verbose_name='Tipo de Widget')),
                ('data_source', models.CharField(max_length=255, verbose_name='Fonte de Dados')),
                ('parameters', models.JSONField(blank=True, null=True, verbose_name='Parâmetros')),
                ('position_x', models.IntegerField(default=0, verbose_name='Posição X')),
                ('position_y', models.IntegerField(default=0, verbose_name='Posição Y')),
                ('width', models.IntegerField(default=1, verbose_name='Largura')),
                ('height', models.IntegerField(default=1, verbose_name='Altura')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='reports.dashboard', verbose_name='Dashboard')),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
                'ordering': ['dashboard', 'position_y', 'position_x'],
            },
        ),
    ]
