# Generated by Django 4.2.10 on 2025-06-09 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_templates_created', to='users.userprofile', verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='reportexecution',
            name='executed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_executions', to='users.userprofile', verbose_name='Executado por'),
        ),
        migrations.AddField(
            model_name='reportexecution',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='reports.report', verbose_name='Relatório'),
        ),
        migrations.AddField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_created', to='users.userprofile', verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='report',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='subscribed_reports', to='users.userprofile', verbose_name='Destinatários'),
        ),
        migrations.AddField(
            model_name='metricvalue',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='reports.metric', verbose_name='Métrica'),
        ),
        migrations.AddField(
            model_name='metric',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics_created', to='users.userprofile', verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_dashboards', to='users.userprofile', verbose_name='Proprietário'),
        ),
        migrations.AlterUniqueTogether(
            name='metricvalue',
            unique_together={('metric', 'date', 'context')},
        ),
    ]
