# Generated by Django 4.2.10 on 2025-06-09 19:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('presential', 'Presencial'), ('video', 'Vídeo'), ('phone', 'Telefone'), ('group', 'Dinâmica em Grupo'), ('technical', 'Técnica')], default='presential', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('scheduled', 'Agendada'), ('confirmed', 'Confirmada'), ('completed', 'Realizada'), ('canceled', 'Cancelada'), ('rescheduled', 'Reagendada'), ('no_show', 'Não Compareceu')], default='scheduled', max_length=20, verbose_name='Status')),
                ('scheduled_date', models.DateTimeField(verbose_name='Data Agendada')),
                ('duration', models.PositiveIntegerField(default=60, help_text='Duração em minutos', verbose_name='Duração')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Local')),
                ('meeting_link', models.URLField(blank=True, null=True, verbose_name='Link da Reunião')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Entrevista',
                'verbose_name_plural': 'Entrevistas',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Pontuação Técnica')),
                ('communication_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Pontuação de Comunicação')),
                ('cultural_fit_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Adequação Cultural')),
                ('strengths', models.TextField(blank=True, null=True, verbose_name='Pontos Fortes')),
                ('weaknesses', models.TextField(blank=True, null=True, verbose_name='Pontos de Melhoria')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comentários Gerais')),
                ('recommendation', models.CharField(choices=[('hire', 'Contratar'), ('consider', 'Considerar'), ('reject', 'Rejeitar'), ('next_stage', 'Próxima Etapa')], max_length=20, verbose_name='Recomendação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Feedback de Entrevista',
                'verbose_name_plural': 'Feedbacks de Entrevistas',
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Pergunta')),
                ('category', models.CharField(choices=[('technical', 'Técnica'), ('behavioral', 'Comportamental'), ('experience', 'Experiência'), ('situational', 'Situacional'), ('cultural', 'Cultural'), ('other', 'Outra')], max_length=20, verbose_name='Categoria')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Pergunta de Entrevista',
                'verbose_name_plural': 'Perguntas de Entrevista',
                'ordering': ['category', 'text'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('start_time', models.TimeField(verbose_name='Hora de Início')),
                ('end_time', models.TimeField(verbose_name='Hora de Término')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Recorrente')),
                ('recurrence_pattern', models.CharField(blank=True, choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('biweekly', 'Quinzenal'), ('monthly', 'Mensal')], max_length=20, null=True, verbose_name='Padrão de Recorrência')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Disponibilidade para Entrevista',
                'verbose_name_plural': 'Disponibilidades para Entrevista',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='InterviewTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Template de Entrevista',
                'verbose_name_plural': 'Templates de Entrevista',
            },
        ),
        migrations.CreateModel(
            name='TemplateQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.interviewquestion', verbose_name='Pergunta')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.interviewtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Pergunta do Template',
                'verbose_name_plural': 'Perguntas do Template',
                'ordering': ['order'],
            },
        ),
    ]
