# Generated by Django 4.2.10 on 2025-06-09 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_initial'),
        ('interviews', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewtemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_created', to='users.userprofile', verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='interviewtemplate',
            name='questions',
            field=models.ManyToManyField(related_name='templates', through='interviews.TemplateQuestion', to='interviews.interviewquestion', verbose_name='Perguntas'),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_schedules', to='users.userprofile', verbose_name='Entrevistador'),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_created', to='users.userprofile', verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='interview',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='interviews.interview', verbose_name='Entrevista'),
        ),
        migrations.AddField(
            model_name='interview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.application', verbose_name='Candidatura'),
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews_conducted', to='users.userprofile', verbose_name='Entrevistador'),
        ),
        migrations.AlterUniqueTogether(
            name='templatequestion',
            unique_together={('template', 'question')},
        ),
    ]
