# Generated by Django 4.2.10 on 2025-06-09 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talent_pool', '0001_initial'),
        ('vacancies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talenttag',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talent_tags_added', to='users.userprofile', verbose_name='Adicionado por'),
        ),
        migrations.AddField(
            model_name='talenttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_tags', to='talent_pool.tag', verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='talenttag',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_tags', to='talent_pool.talent', verbose_name='Talento'),
        ),
        migrations.AddField(
            model_name='talentskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_skills', to='vacancies.skill', verbose_name='Habilidade'),
        ),
        migrations.AddField(
            model_name='talentskill',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_notes_set', related_query_name='talent_note', to='talent_pool.talent', verbose_name='Talento'),
        ),
        migrations.AddField(
            model_name='talentrecommendation',
            name='recommender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations_made', to='users.userprofile', verbose_name='Recomendado por'),
        ),
        migrations.AddField(
            model_name='talentrecommendation',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='talent_pool.talent', verbose_name='Talento'),
        ),
        migrations.AddField(
            model_name='talentrecommendation',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_recommendations', to='vacancies.vacancy', verbose_name='Vaga'),
        ),
        migrations.AddField(
            model_name='talentpool',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talent_pools_created', to='users.userprofile', verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='talentnote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talent_notes_created', to='users.userprofile', verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='talentnote',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='talent_pool.talent', verbose_name='Talento'),
        ),
        migrations.AddField(
            model_name='talent',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='talent_profile', to='users.userprofile', verbose_name='Candidato'),
        ),
        migrations.AddField(
            model_name='talent',
            name='departments_of_interest',
            field=models.ManyToManyField(blank=True, related_name='interested_talents', to='vacancies.department', verbose_name='Departamentos de Interesse'),
        ),
        migrations.AddField(
            model_name='talent',
            name='pools',
            field=models.ManyToManyField(blank=True, related_name='talents', to='talent_pool.talentpool', verbose_name='Bancos de Talentos'),
        ),
        migrations.AddField(
            model_name='talent',
            name='skills',
            field=models.ManyToManyField(related_name='talents', through='talent_pool.TalentSkill', to='vacancies.skill', verbose_name='Habilidades'),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags_created', to='users.userprofile', verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to='users.userprofile', verbose_name='Proprietário'),
        ),
        migrations.AlterUniqueTogether(
            name='talenttag',
            unique_together={('talent', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='talentskill',
            unique_together={('talent', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='talentrecommendation',
            unique_together={('talent', 'vacancy')},
        ),
    ]
