# Generated by Django 4.2.10 on 2025-06-09 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'departamento',
                'verbose_name_plural': 'departamentos',
                'ordering': ['hospital', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('address', models.CharField(max_length=255, verbose_name='endereço')),
                ('city', models.CharField(max_length=100, verbose_name='cidade')),
                ('state', models.CharField(max_length=2, verbose_name='estado')),
                ('zip_code', models.CharField(max_length=10, verbose_name='CEP')),
                ('phone', models.CharField(max_length=20, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='website')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hospital_logos/', verbose_name='logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'hospital',
                'verbose_name_plural': 'hospitais',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'categoria de vaga',
                'verbose_name_plural': 'categorias de vagas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='vacancies.jobcategory', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'habilidade',
                'verbose_name_plural': 'habilidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='descrição')),
                ('requirements', models.TextField(verbose_name='requisitos')),
                ('benefits', models.TextField(blank=True, null=True, verbose_name='benefícios')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicada'), ('closed', 'Fechada'), ('filled', 'Preenchida')], default='draft', max_length=20, verbose_name='status')),
                ('contract_type', models.CharField(choices=[('full_time', 'Tempo integral'), ('part_time', 'Meio período'), ('temporary', 'Temporário'), ('internship', 'Estágio')], default='full_time', max_length=20, verbose_name='tipo de contrato')),
                ('experience_level', models.CharField(choices=[('entry', 'Entrada'), ('junior', 'Júnior'), ('mid', 'Pleno'), ('senior', 'Sênior'), ('specialist', 'Especialista')], default='mid', max_length=20, verbose_name='nível de experiência')),
                ('salary_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='faixa salarial mínima')),
                ('salary_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='faixa salarial máxima')),
                ('is_salary_visible', models.BooleanField(default=False, verbose_name='salário visível')),
                ('location', models.CharField(max_length=200, verbose_name='localização')),
                ('is_remote', models.BooleanField(default=False, verbose_name='remoto')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='data de publicação')),
                ('closing_date', models.DateField(blank=True, null=True, verbose_name='data de encerramento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='contagem de visualizações')),
                ('applications_count', models.PositiveIntegerField(default=0, verbose_name='contagem de candidaturas')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='vacancies.jobcategory', verbose_name='categoria')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies.department', verbose_name='departamento')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies.hospital', verbose_name='hospital')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_vacancies', to=settings.AUTH_USER_MODEL, verbose_name='recrutador')),
                ('skills', models.ManyToManyField(related_name='vacancies', to='vacancies.skill', verbose_name='habilidades')),
            ],
            options={
                'verbose_name': 'vaga',
                'verbose_name_plural': 'vagas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VacancyAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='título')),
                ('file', models.FileField(upload_to='vacancy_attachments/', verbose_name='arquivo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='enviado em')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='vacancies.vacancy', verbose_name='vaga')),
            ],
            options={
                'verbose_name': 'anexo de vaga',
                'verbose_name_plural': 'anexos de vagas',
                'ordering': ['vacancy', 'title'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='vacancies.hospital', verbose_name='hospital'),
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='gerente'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('hospital', 'name')},
        ),
    ]
