# Generated by Django 4.2.7 on 2025-09-16 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_fix_manager_foreign_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='monthly_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Carga horária mensal em horas', null=True, verbose_name='carga horária mensal'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies.department', verbose_name='departamento'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descrição'),
        ),
    ]
